version: 2.1
# See: https://circleci.com/developer/orbs/orb/circleci/docker
orbs:
  docker: circleci/docker@2.4.0

# Reusable commands
# See https://circleci.com/docs/reusing-config/
commands:
  docker-load-ci-test:
    description: Load ci-test and ci-test-test images from workspace
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          step-name: Load images
          command: |
            docker image load < "images/ci-test"
            docker image load < "images/ci-test-test"
  docker-deploy-ci-test:
    description: Push ci-test image to DockerHub
    parameters:
      tag:
        type: string
      full-image-tag:
        type: string
        default: vasdommes/ci_test:<< parameters.tag >>
    steps:
      - docker-load-ci-test
      - run: IMAGE_TAG=vasdommes/ci_test:<< parameters.tag >>
      - run: echo tag=<< parameters.tag >>
      - run: echo full-image-tag=<< parameters.full-image-tag >>
      - run:
          step-name: Login and push to Docker.io
          command: |
            echo $DOCKER_PASSWORD | docker login -u vasdommes --password-stdin
            docker tag ci-test vasdommes/ci_test:<< parameters.tag >>
            # docker tag ci-test vasdommes/ci_test
            docker push vasdommes/ci_test:<< parameters.tag >>
      - run: 
          step-name: Pull and test
          command: |
            docker images
            docker image prune -a
            docker pull vasdommes/ci-test:<< parameters.tag >>
            docker images
            docker run vasdommes/ci-test:<< parameters.tag >> ls
      # - run: docker push ci-test vasdommes/ci_test:<< parameters.tag >>
      # - run: docker image ls
      # - run: echo <<parameters.tag>>
      # - docker/push:
      #     step-name: Docker push vasdommes/ci_test:<< parameters.tag >>
      #     image: vasdommes/ci-test
      #     tag: << parameters.tag >>

# Jobs to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build . --tag ci-test
      - run: docker build . --tag ci-test-test --target test
      - run:
          step-name: Save images to workspace
          command: |
            mkdir -p images
            docker image save -o "images/ci-test" "ci-test"
            docker image save -o "images/ci-test-test" "ci-test-test"
      - persist_to_workspace:
          root: .
          paths:
            - images
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - docker-load-ci-test
      - run: docker run ci-test ls
      - run: docker run ci-test-test ls
          
  deploy-sha:
    executor: docker/docker
    steps:
      - docker-deploy-ci-test:
          tag: $CIRCLE_SHA1
  deploy-master:
    executor: docker/docker
    steps:
      - docker-deploy-ci-test:
          tag: master
  deploy-tag:
    executor: docker/docker
    steps:
      - run: echo $CIRCLE_TAG
      - docker-deploy-ci-test:
          tag: $CIRCLE_TAG
      
      
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-sha:
          requires:
            - build
            - test 
      - deploy-master:
          filters:
            branches:
              only: main
          requires:
            - build
            - test         
      - deploy-tag:
          filters:
            tags:
              # Matching tags: "major.minor.patch", e.g. 2.10.1
              only: /^[0-9]+\.[0-9]+\.[0-9]+/
            # For some reason you need this as well: https://discuss.circleci.com/t/tag-not-triggered-by-circleci-not-filter-in-workflow/32036
            branches:
              ignore: /.*/
          requires:
            - build
            - test
