version: 2.1

# Reusable commands
# See https://circleci.com/docs/reusing-config/
commands:

  docker-load-ci-test:
    description: Load ci-test and ci-test-test images from workspace
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          step-name: Load images
          command: |
            docker image load < "images/ci-test"
            docker image load < "images/ci-test-test"
  
  docker-deploy-ci-test:
    description: Push ci-test image to DockerHub
    parameters:
      tag:
        type: string
    steps:
      - docker-load-ci-test
      - run: echo tag=<< parameters.tag >>
      - run:
          step-name: Login and push to Docker.io
          command: |
            docker login --username vasdommes --password ${DOCKER_PASSWORD} 
            docker tag ci-test vasdommes/ci-test:<< parameters.tag >>
            docker push vasdommes/ci-test:<< parameters.tag >>


# Jobs to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:

  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build . --tag ci-test
      - run: docker build . --tag ci-test-test --target test
      - run:
          step-name: Save images to workspace
          command: |
            mkdir -p images
            docker image save -o "images/ci-test" "ci-test"
            docker image save -o "images/ci-test-test" "ci-test-test"
      - persist_to_workspace:
          root: .
          paths:
            - images
  
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - docker-load-ci-test
      - run: docker run ci-test ls
      - run: docker run ci-test-test ls
          
  deploy-master:
    # executor: docker/docker
    docker:
      - image: cimg/base:stable
    steps:
      - docker-deploy-ci-test:
          tag: master
          
  deploy-tag:
    docker:
      - image: cimg/base:stable
    steps:
      - docker-deploy-ci-test:
          tag: $CIRCLE_TAG
      
      
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:

  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
              
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
              
      - deploy-master:
          filters:
            branches:
              only: main
          requires:
            - build
            - test
            
      - deploy-tag:
          filters:
            # deploy only tags like 2.6.0
            tags:
              only: /^\d+\.\d+\.\d+$/
            # See https://discuss.circleci.com/t/tag-not-triggered-by-circleci-not-filter-in-workflow/32036
            branches:
              ignore: /.*/
          # NB: you have to specify tags filter for all dependencies,
          # See https://circleci.com/docs/configuration-reference/#tags
          requires:
            - build
            - test
